# Generated by Django 3.0.3 on 2020-03-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Book',
        ),
    ]
